description: cp_pipe brighter-fatter kernel calibration construction.
tasks:
  bfkSolve:
    class: lsst.cp.pipe.BrighterFatterKernelSolveTask
    config:
      forceZeroSum: True
      useAmatrix: True
      level: 'AMP'
      fudgeFactor: 0.9
      correlationQuadraticFit: False
      #correlationModelRadius: 3
      #correlationModelSlope: -1.61
      #ignoreAmpsForAveraging: ['C02','C07']
      connections.inputPtc: ptc
      connections.outputBFK: bfk

