description: cp_pipe BIAS calibration construction
tasks:
  isr:
    class: lsst.ip.isr.IsrTask
    config:
      connections.ccdExposure: 'raw'
      connections.outputExposure: 'cpBiasProc'
      doWrite: true
      doBias: false
      doDefect: false
      doVariance: true
      doLinearize: false
      doCrosstalk: false
      doBrighterFatter: false
      doDark: false
      doFlat: false
      doApplyGains: false
      doFringe: false
  cpBiasCombine:
    class: lsst.cp.pipe.cpCombine.CalibCombineTask
    config:
      connections.inputExpHandles: 'cpBiasProc'
      connections.outputData: 'bias'
      calibrationType: 'bias'
      exposureScaling: "Unity"
contracts:
  - isr.doBias == False
  - cpBiasCombine.calibrationType == "bias"
  - cpBiasCombine.exposureScaling == "Unity"
