description: cp_pipe PTC calibration construction.
parameters:
    exposureName: cpPtcProc
    measuredCovariances: cpPtcExtract
tasks:
  isr:
    class: lsst.ip.isr.IsrTask
    config:
      connections.ccdExposure: 'raw'
      connections.newBFKernel: 'bfk'
      connections.outputExposure: parameters.exposureName
      doWrite: true
      doOverscan: true
      doAssembleCcd: true
      doBias: true
      doVariance: true
      doLinearize: true
      doCrosstalk: false
      doBrighterFatter: true
      doDark: true
      doStrayLight: false
      doFlat: false
      doFringe: false
      doApplyGains: false
      #usePtcGains: true
      brighterFatterApplyGain: true
      doFluxConservingBrighterFatterCorrection: False
      doDefect: true
      doNanMasking: true
      doInterpolate: false
      doSaturation: false
      doSaturationInterpolation: false
      growSaturationFootprintSize: 0
      doDeferredCharge: true
      deferredChargeCorrection.useGains: true
      brighterFatterMaxIter: 10
  ptcExtract:
    class: lsst.cp.pipe.ptc.PhotonTransferCurveExtractTask
    config:
      connections.inputExp: parameters.exposureName
      connections.taskMetadata: 'isr_metadata'
      connections.outputCovariances: parameters.measuredCovariances
      #maximumRangeCovariancesAstier: 15
  ptcSolve:
    class: lsst.cp.pipe.ptc.PhotonTransferCurveSolveTask
    config:
      connections.inputCovariances: parameters.measuredCovariances
      connections.outputPtcDataset: ptc
      ptcFitType: FULLCOVARIANCE
      #maximumRangeCovariancesAstier: 15
contracts:
  - ptcSolve.maximumRangeCovariancesAstier == ptcExtract.maximumRangeCovariancesAstier
subsets:
  gainFromFlatPairs:
      subset:
          - isr
          - ptcExtract
      description: gain estimation from pairs of flats at the same exposure time.
      