wdescription: cp_pipe brighter-fatter kernel calibration construction.
tasks:
  bfkSolve:
    class: lsst.cp.pipe.BrighterFatterKernelSolveTask
    config:
      forceZeroSum: True
      useAmatrix: True
      level: 'AMP'
      fudgeFactor: 0.847
      correlationQuadraticFit: False
      correlationModelRadius: 3
      correlationModelSlope: -1.654
      #ignoreAmpsForAveraging: ['C05', 'C07', 'C11']
      connections.inputPtc: ptc
      connections.outputBFK: bfk

