description: cp_pipe brighter-fatter kernel calibration construction.
tasks:
  bfkSolve:
    class: lsst.cp.pipe.BrighterFatterKernelSolveTask
    config:
      forceZeroSum: True
      useAmatrix: True
      level: 'AMP'
      fudgeFactor: 0.706
      correlationQuadraticFit: False
      correlationModelRadius: 3
      correlationModelSlope: -1.631
      #ignoreAmpsForAveraging: ['C05', 'C07', 'C11']
      connections.inputPtc: ptc
      connections.outputBFK: bfk

## These amplifiers are already ignored in the isrTask run function of alternate_branches/chrisfixes, which is why they are all commented out. 